default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: 1

development:
  <<: *default
  database: EC_Seminar_hw_development
  #host: localhost
  #port: 5432

test:
  <<: *default
  database: EC_Seminar_hw_test

production:
  <<: *default
  database: EC_Seminar_hw_production
  #username: postgres
  #password: 1
